"""
Django settings for aghighweb project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import locale
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+fz84dqlz1wty)312w8%cv7z+u!_=m7a@j*mg915y_u4l@ip-c'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'raven.contrib.django.raven_compat',

    'apps.activity',
    'apps.main',
    'apps.announcements',
    'apps.notification',
    'apps.league',
    'apps.access',
    'apps.hamraz',
    'apps.my_school',
    'apps.reports',
    'apps.calendar_app',
    'apps.shop',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'aghighweb.middleware.ACLMiddleware',
    'aghighweb.middleware.DisablePartManager',
]

ROOT_URLCONF = 'aghighweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.context_processor.disable_part',  # ارسال دیکشنری بخش های غیرفعال
            ],
        },
    },
]

WSGI_APPLICATION = 'aghighweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'aghigh_web',
        'USER': 'agu6756v',
        'PASSWORD': 'dfsdfdf#$$^^#QsAD$KxsBgVdzPAU=565kzWG3mVsW',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/


LANGUAGE_CODE = 'fa-ir'
locale.setlocale(locale.LC_ALL, "fa_IR")

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
#
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

SERVER_URL = 'http://127.0.0.1'
SERVER_PORT = 9090

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ACL_EXEMPT_VIEWS = [
    'access_login',
    'access_logout',
    'confirm_code',
]

LOGS_ROOT = os.path.join(BASE_DIR, 'logs')

PAGE_SIZE = 12

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format':
                '[START]-[AT]:%(asctime)s \n' +
                '[LEVEL]:%(levelname)s\n' +
                '[FILE]:%(pathname)s\n' +
                '[LINE]:%(lineno)d\n' +
                '[PROCESS]:%(process)d ' +
                '[THREAD]:%(thread)d\n' +
                '[DETAIL]:%(detail)s\n'
                '[MESSAGE]:%(message)s\n'
                '[END]\n-----------------------------\n'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_ROOT + '/{}.log'.format(datetime.datetime.now().strftime('%Y_%m_%d')),
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'dashboard': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
