from .base import *

DEBUG = True

ALLOWED_HOSTS = ['37.59.208.99']

SERVER_URL = 'http://127.0.0.1'
SERVER_PORT = 9090
SERVER_FULL_URL = SERVER_URL

SERVER_PUBLIC_URL = 'http://37.59.208.99'
SERVER_PUBLIC_PORT = 9090
SERVER_PUBLIC_FULL_URL = SERVER_PUBLIC_URL

if SERVER_PORT is not None:
    SERVER_FULL_URL = SERVER_FULL_URL + ':' + str(SERVER_PORT)

if SERVER_PUBLIC_PORT is not None:
    SERVER_PUBLIC_FULL_URL = SERVER_PUBLIC_FULL_URL + ':' + str(SERVER_PUBLIC_PORT)

MAIN_SERVER_IMAGE_FULL_URL = 'http://aghigh.ayandehsazan.ir:9090'
