# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 08:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBox',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=80)),
                ('user_type', models.CharField(max_length=10)),
                ('user_level', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=350)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('api_user_id', models.PositiveIntegerField(blank=True, default=False, null=True)),
                ('province_id', models.PositiveIntegerField(blank=True, default=False, null=True)),
                ('school_id', models.PositiveIntegerField(blank=True, default=False, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('gender_select', models.CharField(blank=True, max_length=20, null=True)),
                ('role_select', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
